apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: handit-external-secret
  namespace: handit
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: leviosa-express-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: leviosa-express-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: leviosa-express
        property: OPENAI_API_KEY
    - secretKey: JWT_SECRET
      remoteRef:
        key: leviosa-express
        property: JWT_SECRET
    - secretKey: SESSION_SECRET
      remoteRef:
        key: leviosa-express
        property: SESSION_SECRET
    - secretKey: DATABASE_URL
      remoteRef:
        key: leviosa-express
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: leviosa-express
        property: REDIS_URL
    - secretKey: SENDGRID_API_KEY
      remoteRef:
        key: leviosa-express
        property: SENDGRID_API_KEY
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: leviosa-express
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: leviosa-express
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        key: leviosa-express
        property: AWS_DEFAULT_REGION
    - secretKey: AUTH0_ISSUER_BASE_URL
      remoteRef:
        key: leviosa-express
        property: AUTH0_ISSUER_BASE_URL
    - secretKey: AUTH0_CLIENT_ID
      remoteRef:
        key: leviosa-express
        property: AUTH0_CLIENT_ID
    - secretKey: AUTH0_CLIENT_SECRET
      remoteRef:
        key: leviosa-express
        property: AUTH0_CLIENT_SECRET
    - secretKey: AUTH0_AUDIENCE
      remoteRef:
        key: leviosa-express
        property: AUTH0_AUDIENCE
    - secretKey: AUTH0_SECRET
      remoteRef:
        key: leviosa-express
        property: AUTH0_SECRET
    - secretKey: VERCEL_API_KEY
      remoteRef:
        key: leviosa-express
        property: VERCEL_API_KEY
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: leviosa-express
        property: ANTHROPIC_API_KEY