# Default values for handit-ai
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  environment: "dev"
  domain: "handit.ai"
  imageRegistry: ""  # Will be set per environment
  imagePullSecrets: []
  
  # External dependencies
  postgresql:
    host: ""  # Set in environment-specific values
    port: 5432
    database: "handit"
    existingSecret: "handit-postgres-secret"
    secretKeys:
      username: "username"
      password: "password"
  
  redis:
    host: ""  # Set in environment-specific values
    port: 6379
    existingSecret: "handit-redis-secret"
    secretKeys:
      password: "password"

# Sub-chart configurations
handit-api:
  enabled: true
  replicaCount: 2
  image:
    repository: handit-api
    tag: latest
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
  
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

handit-dashboard:
  enabled: true
  replicaCount: 2
  image:
    repository: handit-dashboard
    tag: latest
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 3000
  
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80

handit-worker:
  enabled: true
  replicaCount: 1
  image:
    repository: handit-api  # Uses same image as API
    tag: latest
    pullPolicy: IfNotPresent
  
  command: ["node", "src/workers/metricWorker.js"]
  
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

# Ingress configuration
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/success-codes: 200-399
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  hosts:
    - host: api.handit.ai
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: handit-api
            port: 8080
    - host: dashboard.handit.ai
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: handit-dashboard
            port: 3000
  tls: []  # Managed by ALB

# Service Account configuration
# Note: We use Leviosa's existing service account (leviosa-express-sa)
serviceAccount:
  create: false  # Don't create, use existing
  name: "leviosa-express-sa"

# External Secrets configuration
# Note: We use Leviosa's existing external secrets (leviosa-express-secrets)
# No configuration needed here as we're reusing Leviosa's setup