# Development environment values for handit-ai

global:
  environment: "dev"
  domain: "dev-unison.totango.com"  # Using leviosa's domain pattern
  imageRegistry: "537124952465.dkr.ecr.eu-west-1.amazonaws.com"  # Leviosa dev AWS account
  
  postgresql:
    host: "handit-postgres-dev.cluster-abc123.eu-west-1.rds.amazonaws.com"  # Replace with actual RDS endpoint
  
  redis:
    host: "handit-redis-dev.abc123.euw1.cache.amazonaws.com"  # Replace with actual ElastiCache endpoint

handit-api:
  image:
    tag: "dev-latest"
  
  env:
    - name: NODE_ENV
      value: "development"
    - name: LOG_LEVEL
      value: "debug"
    - name: CORS_ORIGIN
      value: "https://handit.dev-unison.totango.com"

handit-dashboard:
  image:
    tag: "dev-latest"
  
  env:
    - name: NEXT_PUBLIC_API_URL
      value: "https://handit-api.dev-unison.totango.com/api"
    - name: NEXT_PUBLIC_ENVIRONMENT
      value: "development"

handit-worker:
  image:
    tag: "dev-latest"
  replicaCount: 1
  autoscaling:
    enabled: false  # Disable autoscaling in dev

ingress:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:537124952465:certificate/dev-cert-id"  # Replace with actual cert
    alb.ingress.kubernetes.io/group.name: "leviosa-dev"  # Share ALB with leviosa
    alb.ingress.kubernetes.io/group.order: "200"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/load-balancer-name: "leviosa-dev-alb"
    alb.ingress.kubernetes.io/tags: "Environment=dev,Team=handit"
  hosts:
    - host: handit-api.dev-unison.totango.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: handit-api
            port: 8080
    - host: handit.dev-unison.totango.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: handit-dashboard
            port: 3000

# Development-specific resource limits (lower than prod)
handit-api:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

handit-dashboard:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi

# Using Leviosa's existing service account and secrets
# No additional configuration needed