# Production environment values for handit-ai

global:
  environment: "prod"
  domain: "unison.totango.com"  # Using leviosa's production domain
  imageRegistry: "904233102192.dkr.ecr.eu-west-1.amazonaws.com"  # Leviosa prod AWS account
  
  postgresql:
    host: "handit-postgres-prod.cluster-xyz789.eu-west-1.rds.amazonaws.com"  # Replace with actual RDS endpoint
  
  redis:
    host: "handit-redis-prod.xyz789.euw1.cache.amazonaws.com"  # Replace with actual ElastiCache endpoint

handit-api:
  replicaCount: 2
  image:
    tag: "fix-cors-1753738392"  # Fixed version with CORS, migration and health endpoint
  
  env:
    - name: LOG_LEVEL
      value: "info"
    - name: CORS_ORIGIN
      value: "https://handit.unison.totango.com"
    - name: OPENAI_API_KEY
      value: "dummy-key-using-bedrock"
    - name: PORT
      value: "8080"
  
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  
  autoscaling:
    minReplicas: 2
    maxReplicas: 5

handit-dashboard:
  replicaCount: 2
  image:
    tag: "fix-api-url"
  
  env:
    - name: NEXT_PUBLIC_API_URL
      value: "https://handit-api.unison.totango.com/api"
    - name: NEXT_PUBLIC_ENVIRONMENT
      value: "production"
  
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  
  autoscaling:
    minReplicas: 2
    maxReplicas: 4

handit-worker:
  replicaCount: 1
  image:
    tag: "latest"
  
  env:
    - name: OPENAI_API_KEY
      value: "dummy-key-using-bedrock"
  
  autoscaling:
    minReplicas: 1
    maxReplicas: 3

ingress:
  annotations:
    # Certificate will be auto-discovered by AWS ALB controller based on domain
    alb.ingress.kubernetes.io/group.name: "leviosa-prod"  # Share ALB with leviosa
    alb.ingress.kubernetes.io/group.order: "200"
    alb.ingress.kubernetes.io/load-balancer-name: "leviosa-prod-alb"
    alb.ingress.kubernetes.io/tags: "Environment=prod,Team=handit"
  hosts:
    - host: handit-api.unison.totango.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: handit-api
            port: 8080
    - host: handit.unison.totango.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: handit-dashboard
            port: 3000

# Production-specific monitoring
serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics

# Using Leviosa's existing service account and secrets
# No additional configuration needed