apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: handit-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: handit-secretstore
    kind: SecretStore
  target:
    name: leviosa-express-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: external-secrets