apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: handit-secretstore
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: handit-sa