steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--set-secrets'
      - 'DB_USERNAME=DB_USERNAME:latest'
      - '--set-secrets'
      - 'DB_PASSWORD=DB_PASSWORD:latest'
      - '--set-secrets'
      - 'DB_NAME=DB_NAME:latest'
      - '--set-secrets'
      - 'DB_NAME_TEST=DB_NAME_TEST:latest'
      - '--set-secrets'
      - 'DB_HOST=DB_HOST:latest'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest'
      - '--set-secrets'
      - 'JWT_SECRET=JWT_SECRET:latest'
      - '--set-secrets'
      - 'SENDGRID_API_KEY=SENDGRID_API_KEY:latest'
      - '--set-secrets'
      - 'EMAIL_FROM=EMAIL_FROM:latest'
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'
      - '--set-secrets'
      - 'REDIS_URL=REDIS_URL:latest'
      - '--set-secrets'
      - 'TOGETHER_API_KEY=TOGETHER_API_KEY:latest'
      - '--network=default'
      - '--subnet=default'
      - '--platform=managed'
      - '--memory=3Gi'
      - '--set-env-vars=NODE_OPTIONS=--max-old-space-size=1536'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: handit-api
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _TRIGGER_ID: 977ff36f-966a-4ac2-a276-ef7e79e63af1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - handit-api